name: Sync Fork

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *' #Runs every 5 minute
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/viktornoskire/group_back-end_kino.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
